// <auto-generated />
using System;
using Final_project_crud_endpoints.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Final_project_crud_endpoints.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240111122650_subcategories of Smart gadgets category")]
    partial class subcategoriesofSmartgadgetscategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Discover cutting-edge smartphones and accessories for seamless connectivity. Elevate your mobile experience with the latest technology, from feature-packed smartphones to stylish and functional accessories that enhance usability and style.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartphones and accessories"
                        },
                        new
                        {
                            Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Explore the future with smart gadgets. Experience seamless integration of technology into daily life with innovative devices, from smart home solutions to wearables, enhancing convenience, connectivity, and efficiency.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smart gadgets"
                        },
                        new
                        {
                            Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Empower your digital journey with notebooks, PCs, and tablets. Find the perfect balance of performance and portability. Choose from a diverse range of computing solutions tailored to your needs.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Notebooks, PCs, tablets"
                        },
                        new
                        {
                            Id = new Guid("cdb59c3a-487c-42e5-bc0e-58ad5cfb93d3"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elevate your gaming experience with cutting-edge products for gamers. Unleash the power of high-performance hardware, immersive accessories, and advanced gear designed to take your gaming to the next level.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Products for gamers"
                        },
                        new
                        {
                            Id = new Guid("f6b3406c-6046-486f-8ba8-a896ac26fe90"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Transform your kitchen with modern convenience. Explore a range of innovative kitchen appliances, from efficient cookware to time-saving gadgets, enhancing your culinary experience with style and functionality.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kitchen appliances"
                        },
                        new
                        {
                            Id = new Guid("9214f8c7-7c65-4c6d-852c-9f6f6c232a21"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Upgrade your home with efficient and modern home appliances. Explore a diverse range of devices, from energy-efficient appliances to smart home solutions, making everyday tasks convenient and your living space more comfortable.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Home appliances"
                        },
                        new
                        {
                            Id = new Guid("d2bc155a-9de0-40ed-b3e7-1a4c0983c2e5"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Discover a world of well-being with beauty and health equipment. From advanced skincare devices to fitness technology, elevate your self-care routine with innovative products designed to promote beauty and wellness.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Beauty and health equipment"
                        },
                        new
                        {
                            Id = new Guid("68a906fa-2d2e-4bb7-a93a-9d12305b07a3"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Immerse yourself in entertainment with TV, audio, and photo solutions. Explore stunning visuals, crystal-clear sound, and capture moments with cutting-edge technology, enhancing your audio-visual experience at home.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TV, audio and photo"
                        },
                        new
                        {
                            Id = new Guid("b654a618-ec4f-4d7f-a90e-0c5ea3eaa0e1"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elevate your gaming experience with cutting-edge products for gamers. Unleash the power of high-performance hardware, immersive accessories, and advanced gear designed to take your gaming to the next level.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hobby and entertainment"
                        },
                        new
                        {
                            Id = new Guid("8ff9b1e2-0630-4821-aa16-13937e509ee2"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Immerse yourself in entertainment with TV, audio, and photo solutions. Explore stunning visuals, crystal-clear sound, and capture moments with cutting-edge technology, enhancing your audio-visual experience at home.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Construction supplies"
                        },
                        new
                        {
                            Id = new Guid("3a0c847a-8ce1-4f14-916f-3e4b899d19d9"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Immerse yourself in entertainment with TV, audio, and photo solutions. Explore stunning visuals, crystal-clear sound, and capture moments with cutting-edge technology, enhancing your audio-visual experience at home.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Automotive products"
                        },
                        new
                        {
                            Id = new Guid("5b9e0bd5-927c-4d4b-9534-9b67ef7235b2"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Upgrade your home with efficient and modern home appliances. Explore a diverse range of devices, from energy-efficient appliances to smart home solutions, making everyday tasks convenient and your living space more comfortable.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "House and garden"
                        });
                });

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color_Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b24804b-9a8f-4d33-9f43-8c461e4dbf11"),
                            Color_Code = "#000000",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "black"
                        },
                        new
                        {
                            Id = new Guid("9c327764-bf90-4b8b-8c38-370cb3aa2a5a"),
                            Color_Code = "#ffffff",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "white"
                        },
                        new
                        {
                            Id = new Guid("8a4c94f8-2437-4e89-9075-56bbcf19c0e9"),
                            Color_Code = "#a52a2a",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "brown"
                        },
                        new
                        {
                            Id = new Guid("af15118a-95ac-487a-b103-c9a0a1918c25"),
                            Color_Code = "#0000ff",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "blue"
                        },
                        new
                        {
                            Id = new Guid("6c1d50fc-b6eb-4d76-ba7e-81a7811ea15f"),
                            Color_Code = "#ff0000",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "red"
                        },
                        new
                        {
                            Id = new Guid("3e20ac3a-c156-4f60-b0b4-e1f1c205e24d"),
                            Color_Code = "#808080",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "gray"
                        },
                        new
                        {
                            Id = new Guid("db1ef4d9-5b95-41a3-8bfb-7f01f8a50f32"),
                            Color_Code = "#008000",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "green"
                        },
                        new
                        {
                            Id = new Guid("45e0cbf9-aa2a-44a4-93a1-bf4d3aa623ce"),
                            Color_Code = "#ffff00",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "yellow"
                        },
                        new
                        {
                            Id = new Guid("8640c057-8997-4b16-b3dd-7c3d3c2e1a12"),
                            Color_Code = "#2f4f4f",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "darkslategray"
                        },
                        new
                        {
                            Id = new Guid("7a9d04e8-1a22-4aae-8232-62f5a0c28b87"),
                            Color_Code = "#663399",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "rebeccapurple"
                        },
                        new
                        {
                            Id = new Guid("2ff83d6b-6c95-4f7d-9c64-60e406a057a1"),
                            Color_Code = "#ffe4c4",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "bisque"
                        },
                        new
                        {
                            Id = new Guid("9a305d7f-5c8f-4fe1-9c0d-d8a8eb4a17c3"),
                            Color_Code = "#ffe4c4",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "bisque"
                        },
                        new
                        {
                            Id = new Guid("c80a742d-12db-4a19-a0e8-44c67f7fb21a"),
                            Color_Code = "#00ced1",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "darkturquoise"
                        });
                });

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Discount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOffer")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManufacturedIn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Current_Category_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Current_Category_Id");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a92b0cd-7d8d-4ee9-8a82-4f482b4c4a95"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Smartphones have become indispensable in our daily lives, serving as multifunctional devices that go beyond mere communication.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = new Guid("d7f7fc67-7e84-4b72-90eb-99ab9a1fe1a8"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Dive into superior sound quality with our sleek and comfortable headphones. Whether wireless or wired, enjoy immersive audio and noise cancellation, making them an essential accessory for music lovers and gamers alike.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = new Guid("23f8c33a-16fc-4eaa-9c3e-b97e130dce9d"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Experience simplicity and reliability with our push-button phones. Effortlessly dial numbers with user-friendly keypads, ensuring quick and convenient communication. These phones combine classic design with modern functionality, providing a straightforward and dependable means of staying connected in the digital age.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Push-button phones"
                        },
                        new
                        {
                            Id = new Guid("c1a5eab4-fcb5-4a76-8447-cbe95f4a4cc4"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Stay connected effortlessly with our range of home and office phones. Designed for convenience, these phones blend functionality with sleek aesthetics, offering reliable communication solutions. Whether you're organizing your home or optimizing your office, our phones provide crystal-clear audio and user-friendly features for seamless conversations.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Home and office phones"
                        },
                        new
                        {
                            Id = new Guid("9f2ef2e1-15a5-4c93-bbfb-15a95c50d5e8"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Elevate your mobile experience with our diverse range of phone accessories. From stylish cases that provide protection to chargers that keep you powered up, our collection enhances the functionality and style of your device. Explore a variety of accessories, including screen protectors, stands, and innovative gadgets, ensuring your phone is both personalized and optimized for your lifestyle.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Phone accessories"
                        },
                        new
                        {
                            Id = new Guid("e3e9a6a7-6f1c-43bb-b0ac-6f646fa307fd"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Enhance your audio experience with our range of headphone accessories. From comfortable ear cushions to tangle-free cables, our collection ensures optimal comfort and convenience. Explore accessories like stylish cases, adapters, and stands to complement your headphones, allowing you to personalize and elevate your listening setup effortlessly.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Headphone accessories"
                        },
                        new
                        {
                            Id = new Guid("59053d5f-cd74-4e42-8e4a-42ebd80d1c1d"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Explore the versatility of modern technology with our range of tablets. Sleek and portable, these devices offer a seamless blend of productivity and entertainment. Whether you're browsing, working, or enjoying multimedia content, our tablets deliver stunning visuals and efficient performance. Stay connected on the go with these compact and feature-rich companions, redefining the way you experience digital mobility.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = new Guid("d4b8a5c2-c4db-4e3f-aa3f-3d389f5a1aeb"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Embrace the future of wearable technology with our smartwatches. Seamlessly blending style and functionality, these devices go beyond traditional timekeeping. Monitor your health, receive notifications, and stay connected with cutting-edge features. With sleek designs and intuitive interfaces, our smartwatches empower you to navigate your day effortlessly, combining fashion and innovation on your wrist.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smart watches"
                        },
                        new
                        {
                            Id = new Guid("07ff4b23-b509-41e2-b932-37eae200181c"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Elevate your fitness and style with our smart bracelets. These sleek, wearable devices seamlessly integrate technology into your lifestyle. Track your health and fitness metrics, receive notifications, and stay connected on the go. Designed for comfort and performance, our smart bracelets are the perfect companions for those who prioritize both wellness and fashion in their daily lives.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smart bracelets"
                        },
                        new
                        {
                            Id = new Guid("8d60aefa-e6cb-4b90-9e90-0de7d4d01a7b"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Transform your surroundings with our collection of smart equipment. From intelligent home devices to cutting-edge gadgets, these products seamlessly integrate technology into your daily life. Enjoy enhanced efficiency, connectivity, and control as our smart equipment empowers you to create a modern and intelligent living or working space. Explore the future of convenience with our innovative selection.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smart equipment"
                        },
                        new
                        {
                            Id = new Guid("b0f7748c-02cf-46e3-9c82-412c284240d1"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Dive into a world of immersive audio with our premium headphones. Offering crystal-clear sound, comfortable designs, and sleek aesthetics, our headphones elevate your listening experience. Whether you're a music enthusiast, gamer, or on-the-go professional, our range includes wireless and wired options, ensuring a perfect fit for every lifestyle. Experience the power of superior sound quality with our cutting-edge headphone collection.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = new Guid("431bbfe3-7e5d-4d90-b590-e20fb631ac3d"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Accessorize your style and stay punctual with our curated selection of wristwatches. From classic elegance to modern innovation, our collection offers a timepiece for every occasion. Choose from a variety of designs, materials, and features, ensuring both functionality and fashion. Embrace the art of timekeeping with our wristwatches, where precision meets personal expression.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Wristwatches"
                        },
                        new
                        {
                            Id = new Guid("7587c8cc-2cc2-4eb4-8c87-48f540a759e1"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Embark on seamless journeys with our diverse transportation solutions. From sleek electric cars to reliable bicycles and innovative scooters, our collection is designed for modern mobility. Discover eco-friendly options and cutting-edge technologies that redefine how you move. Whether commuting or exploring, our transportation offerings prioritize efficiency, sustainability, and a connected travel experience.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = new Guid("aab6cbec-dc48-4d4f-a480-137c3e8605c9"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Empower your child with a blend of fun and safety using our children's smartwatches. These wearable gadgets offer a secure connection, allowing you to stay in touch while granting your child a sense of independence. Packed with features like GPS tracking, calling, and safety alerts, our smartwatches provide peace of mind for parents and an exciting, interactive experience for kids. Nurture their curiosity with technology that's both entertaining and secure.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Children's smart watches"
                        });
                });

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Subcategory", b =>
                {
                    b.HasOne("Final_project_crud_endpoints.DataBase.Entities.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("Current_Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
