// <auto-generated />
using System;
using Final_project_crud_endpoints.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Final_project_crud_endpoints.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240112084941_subcategories of Home appliances category")]
    partial class subcategoriesofHomeappliancescategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Discover cutting-edge smartphones and accessories for seamless connectivity. Elevate your mobile experience with the latest technology, from feature-packed smartphones to stylish and functional accessories that enhance usability and style.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartphones and accessories"
                        },
                        new
                        {
                            Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Explore the future with smart gadgets. Experience seamless integration of technology into daily life with innovative devices, from smart home solutions to wearables, enhancing convenience, connectivity, and efficiency.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smart gadgets"
                        },
                        new
                        {
                            Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Empower your digital journey with notebooks, PCs, and tablets. Find the perfect balance of performance and portability. Choose from a diverse range of computing solutions tailored to your needs.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Notebooks, PCs, tablets"
                        },
                        new
                        {
                            Id = new Guid("cdb59c3a-487c-42e5-bc0e-58ad5cfb93d3"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elevate your gaming experience with cutting-edge products for gamers. Unleash the power of high-performance hardware, immersive accessories, and advanced gear designed to take your gaming to the next level.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Products for gamers"
                        },
                        new
                        {
                            Id = new Guid("f6b3406c-6046-486f-8ba8-a896ac26fe90"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Transform your kitchen with modern convenience. Explore a range of innovative kitchen appliances, from efficient cookware to time-saving gadgets, enhancing your culinary experience with style and functionality.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kitchen appliances"
                        },
                        new
                        {
                            Id = new Guid("9214f8c7-7c65-4c6d-852c-9f6f6c232a21"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Upgrade your home with efficient and modern home appliances. Explore a diverse range of devices, from energy-efficient appliances to smart home solutions, making everyday tasks convenient and your living space more comfortable.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Home appliances"
                        },
                        new
                        {
                            Id = new Guid("d2bc155a-9de0-40ed-b3e7-1a4c0983c2e5"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Discover a world of well-being with beauty and health equipment. From advanced skincare devices to fitness technology, elevate your self-care routine with innovative products designed to promote beauty and wellness.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Beauty and health equipment"
                        },
                        new
                        {
                            Id = new Guid("68a906fa-2d2e-4bb7-a93a-9d12305b07a3"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Immerse yourself in entertainment with TV, audio, and photo solutions. Explore stunning visuals, crystal-clear sound, and capture moments with cutting-edge technology, enhancing your audio-visual experience at home.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "TV, audio and photo"
                        },
                        new
                        {
                            Id = new Guid("b654a618-ec4f-4d7f-a90e-0c5ea3eaa0e1"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elevate your gaming experience with cutting-edge products for gamers. Unleash the power of high-performance hardware, immersive accessories, and advanced gear designed to take your gaming to the next level.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hobby and entertainment"
                        },
                        new
                        {
                            Id = new Guid("8ff9b1e2-0630-4821-aa16-13937e509ee2"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Immerse yourself in entertainment with TV, audio, and photo solutions. Explore stunning visuals, crystal-clear sound, and capture moments with cutting-edge technology, enhancing your audio-visual experience at home.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Construction supplies"
                        },
                        new
                        {
                            Id = new Guid("3a0c847a-8ce1-4f14-916f-3e4b899d19d9"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Immerse yourself in entertainment with TV, audio, and photo solutions. Explore stunning visuals, crystal-clear sound, and capture moments with cutting-edge technology, enhancing your audio-visual experience at home.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Automotive products"
                        },
                        new
                        {
                            Id = new Guid("5b9e0bd5-927c-4d4b-9534-9b67ef7235b2"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Upgrade your home with efficient and modern home appliances. Explore a diverse range of devices, from energy-efficient appliances to smart home solutions, making everyday tasks convenient and your living space more comfortable.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "House and garden"
                        });
                });

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Color", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color_Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Color");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b24804b-9a8f-4d33-9f43-8c461e4dbf11"),
                            Color_Code = "#000000",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "black"
                        },
                        new
                        {
                            Id = new Guid("9c327764-bf90-4b8b-8c38-370cb3aa2a5a"),
                            Color_Code = "#ffffff",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "white"
                        },
                        new
                        {
                            Id = new Guid("8a4c94f8-2437-4e89-9075-56bbcf19c0e9"),
                            Color_Code = "#a52a2a",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "brown"
                        },
                        new
                        {
                            Id = new Guid("af15118a-95ac-487a-b103-c9a0a1918c25"),
                            Color_Code = "#0000ff",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "blue"
                        },
                        new
                        {
                            Id = new Guid("6c1d50fc-b6eb-4d76-ba7e-81a7811ea15f"),
                            Color_Code = "#ff0000",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "red"
                        },
                        new
                        {
                            Id = new Guid("3e20ac3a-c156-4f60-b0b4-e1f1c205e24d"),
                            Color_Code = "#808080",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "gray"
                        },
                        new
                        {
                            Id = new Guid("db1ef4d9-5b95-41a3-8bfb-7f01f8a50f32"),
                            Color_Code = "#008000",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "green"
                        },
                        new
                        {
                            Id = new Guid("45e0cbf9-aa2a-44a4-93a1-bf4d3aa623ce"),
                            Color_Code = "#ffff00",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "yellow"
                        },
                        new
                        {
                            Id = new Guid("8640c057-8997-4b16-b3dd-7c3d3c2e1a12"),
                            Color_Code = "#2f4f4f",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "darkslategray"
                        },
                        new
                        {
                            Id = new Guid("7a9d04e8-1a22-4aae-8232-62f5a0c28b87"),
                            Color_Code = "#663399",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "rebeccapurple"
                        },
                        new
                        {
                            Id = new Guid("2ff83d6b-6c95-4f7d-9c64-60e406a057a1"),
                            Color_Code = "#ffe4c4",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "bisque"
                        },
                        new
                        {
                            Id = new Guid("9a305d7f-5c8f-4fe1-9c0d-d8a8eb4a17c3"),
                            Color_Code = "#ffe4c4",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "bisque"
                        },
                        new
                        {
                            Id = new Guid("c80a742d-12db-4a19-a0e8-44c67f7fb21a"),
                            Color_Code = "#00ced1",
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "darkturquoise"
                        });
                });

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Discount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOffer")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManufacturedIn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Subcategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Current_Category_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Current_Category_Id");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a92b0cd-7d8d-4ee9-8a82-4f482b4c4a95"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Smartphones have become indispensable in our daily lives, serving as multifunctional devices that go beyond mere communication.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = new Guid("d7f7fc67-7e84-4b72-90eb-99ab9a1fe1a8"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Dive into superior sound quality with our sleek and comfortable headphones. Whether wireless or wired, enjoy immersive audio and noise cancellation, making them an essential accessory for music lovers and gamers alike.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = new Guid("23f8c33a-16fc-4eaa-9c3e-b97e130dce9d"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Experience simplicity and reliability with our push-button phones. Effortlessly dial numbers with user-friendly keypads, ensuring quick and convenient communication. These phones combine classic design with modern functionality, providing a straightforward and dependable means of staying connected in the digital age.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Push-button phones"
                        },
                        new
                        {
                            Id = new Guid("c1a5eab4-fcb5-4a76-8447-cbe95f4a4cc4"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Stay connected effortlessly with our range of home and office phones. Designed for convenience, these phones blend functionality with sleek aesthetics, offering reliable communication solutions. Whether you're organizing your home or optimizing your office, our phones provide crystal-clear audio and user-friendly features for seamless conversations.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Home and office phones"
                        },
                        new
                        {
                            Id = new Guid("9f2ef2e1-15a5-4c93-bbfb-15a95c50d5e8"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Elevate your mobile experience with our diverse range of phone accessories. From stylish cases that provide protection to chargers that keep you powered up, our collection enhances the functionality and style of your device. Explore a variety of accessories, including screen protectors, stands, and innovative gadgets, ensuring your phone is both personalized and optimized for your lifestyle.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Phone accessories"
                        },
                        new
                        {
                            Id = new Guid("e3e9a6a7-6f1c-43bb-b0ac-6f646fa307fd"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Enhance your audio experience with our range of headphone accessories. From comfortable ear cushions to tangle-free cables, our collection ensures optimal comfort and convenience. Explore accessories like stylish cases, adapters, and stands to complement your headphones, allowing you to personalize and elevate your listening setup effortlessly.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Headphone accessories"
                        },
                        new
                        {
                            Id = new Guid("59053d5f-cd74-4e42-8e4a-42ebd80d1c1d"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("4c0298b4-09c2-46e1-8baa-10b8395ebd94"),
                            Description = "Explore the versatility of modern technology with our range of tablets. Sleek and portable, these devices offer a seamless blend of productivity and entertainment. Whether you're browsing, working, or enjoying multimedia content, our tablets deliver stunning visuals and efficient performance. Stay connected on the go with these compact and feature-rich companions, redefining the way you experience digital mobility.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = new Guid("d4b8a5c2-c4db-4e3f-aa3f-3d389f5a1aeb"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Embrace the future of wearable technology with our smartwatches. Seamlessly blending style and functionality, these devices go beyond traditional timekeeping. Monitor your health, receive notifications, and stay connected with cutting-edge features. With sleek designs and intuitive interfaces, our smartwatches empower you to navigate your day effortlessly, combining fashion and innovation on your wrist.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smart watches"
                        },
                        new
                        {
                            Id = new Guid("07ff4b23-b509-41e2-b932-37eae200181c"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Elevate your fitness and style with our smart bracelets. These sleek, wearable devices seamlessly integrate technology into your lifestyle. Track your health and fitness metrics, receive notifications, and stay connected on the go. Designed for comfort and performance, our smart bracelets are the perfect companions for those who prioritize both wellness and fashion in their daily lives.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smart bracelets"
                        },
                        new
                        {
                            Id = new Guid("8d60aefa-e6cb-4b90-9e90-0de7d4d01a7b"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Transform your surroundings with our collection of smart equipment. From intelligent home devices to cutting-edge gadgets, these products seamlessly integrate technology into your daily life. Enjoy enhanced efficiency, connectivity, and control as our smart equipment empowers you to create a modern and intelligent living or working space. Explore the future of convenience with our innovative selection.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smart equipment"
                        },
                        new
                        {
                            Id = new Guid("b0f7748c-02cf-46e3-9c82-412c284240d1"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Dive into a world of immersive audio with our premium headphones. Offering crystal-clear sound, comfortable designs, and sleek aesthetics, our headphones elevate your listening experience. Whether you're a music enthusiast, gamer, or on-the-go professional, our range includes wireless and wired options, ensuring a perfect fit for every lifestyle. Experience the power of superior sound quality with our cutting-edge headphone collection.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = new Guid("431bbfe3-7e5d-4d90-b590-e20fb631ac3d"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Accessorize your style and stay punctual with our curated selection of wristwatches. From classic elegance to modern innovation, our collection offers a timepiece for every occasion. Choose from a variety of designs, materials, and features, ensuring both functionality and fashion. Embrace the art of timekeeping with our wristwatches, where precision meets personal expression.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Wristwatches"
                        },
                        new
                        {
                            Id = new Guid("7587c8cc-2cc2-4eb4-8c87-48f540a759e1"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Embark on seamless journeys with our diverse transportation solutions. From sleek electric cars to reliable bicycles and innovative scooters, our collection is designed for modern mobility. Discover eco-friendly options and cutting-edge technologies that redefine how you move. Whether commuting or exploring, our transportation offerings prioritize efficiency, sustainability, and a connected travel experience.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = new Guid("aab6cbec-dc48-4d4f-a480-137c3e8605c9"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("a1e01df1-f0ef-4e89-a68b-3cd32bfbc04f"),
                            Description = "Empower your child with a blend of fun and safety using our children's smartwatches. These wearable gadgets offer a secure connection, allowing you to stay in touch while granting your child a sense of independence. Packed with features like GPS tracking, calling, and safety alerts, our smartwatches provide peace of mind for parents and an exciting, interactive experience for kids. Nurture their curiosity with technology that's both entertaining and secure.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Children's smart watches"
                        },
                        new
                        {
                            Id = new Guid("0a273bfb-28e6-4d34-a497-6ef2e24e4b5a"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            Description = "Unleash productivity and creativity with our diverse range of laptops. From sleek ultrabooks to powerful gaming machines, our collection caters to every need. Experience cutting-edge technology, vibrant displays, and efficient performance in portable designs. Whether you're a professional on the go or a content creator pushing boundaries, our laptops offer a perfect blend of style, power, and versatility for the modern user.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("6f1d8a61-5b88-4e67-a11f-651b3d09a432"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            Description = "Experience the power of innovation with our comprehensive range of computers. From sleek desktops to versatile all-in-ones, our collection caters to diverse needs. Explore high-performance PCs designed for gaming, creative endeavors, or professional tasks. Whether you seek cutting-edge technology, powerful processing, or seamless connectivity, our computers deliver a perfect balance of performance and reliability for the modern computing experience.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Computers"
                        },
                        new
                        {
                            Id = new Guid("2d61c82b-9ba7-4528-9e14-d8de745f32b3"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            Description = "Immerse yourself in vivid visuals and enhanced productivity with our selection of monitors. From sleek designs to high-resolution displays, our collection caters to diverse needs. Whether you're a gamer, designer, or professional, our monitors offer crisp images, fast refresh rates, and ergonomic features for a seamless viewing experience. Elevate your workspace or gaming setup with technology that brings clarity and efficiency to your screen.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = new Guid("e2f1a8b3-58e8-4962-a7b8-9e7c3ecb301c"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            Description = "Build and upgrade with confidence using our comprehensive selection of computer parts. Explore a wide range of components, from powerful processors and graphics cards to reliable storage solutions and high-speed memory. Whether you're customizing your gaming rig or enhancing your workstation, our collection ensures top-tier performance, compatibility, and reliability for all your computing needs.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Computer parts"
                        },
                        new
                        {
                            Id = new Guid("63ad6b9b-4b3a-4b1f-b823-276db0a0c28f"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            Description = "Optimize connectivity and communication with our advanced network equipment. From routers and switches to access points and modems, our collection is designed to enhance your network performance. Enjoy seamless data transfer, secure connections, and reliable internet access for both home and business environments. Explore cutting-edge technology that ensures a fast, stable, and secure network infrastructure tailored to your connectivity needs.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Network equipment"
                        },
                        new
                        {
                            Id = new Guid("1f9db05a-b5cc-4ea7-8e6d-93e12b5b8d5d"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            Description = "Discover the perfect blend of portability and performance with our versatile tablets. From sleek designs to vibrant displays, our collection offers a range of options to suit your digital lifestyle. Ideal for work, entertainment, or creativity on the go, our tablets feature powerful processors, stunning graphics, and intuitive interfaces. Stay connected and productive with these compact devices that redefine the way you experience digital mobility.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tablets"
                        },
                        new
                        {
                            Id = new Guid("a85e1a45-741c-47b7-8dfb-df7f5e87c76b"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            Description = "Elevate your computing experience with our extensive range of computer accessories. From ergonomic peripherals like keyboards and mice to essential adapters, stylish laptop bags, and cutting-edge external drives – our collection enhances functionality and style. Explore accessories that complement your work or gaming setup, providing convenience and efficiency in every click. Personalize your computing space with the latest and most innovative computer accessories.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Computer accessories"
                        },
                        new
                        {
                            Id = new Guid("77d68ed5-b2cb-41a3-84f0-c6d0cbfb11a0"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            Description = "Dive into the world of gaming with our cutting-edge video game equipment. From high-performance gaming consoles and controllers to immersive virtual reality systems, our collection caters to enthusiasts of all levels. Experience top-notch graphics, precision controls, and seamless gameplay with our advanced gaming gear. Whether you're a casual gamer or a competitive player, our equipment ensures an unparalleled and thrilling gaming experience.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Video game equipment"
                        },
                        new
                        {
                            Id = new Guid("1eb107f7-8525-4ed0-af50-8e01f7731d0b"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            Description = "Enhance your computing setup with our diverse range of peripheral equipment. From ergonomic keyboards and precision mice to high-resolution monitors and versatile docking stations, our collection is designed to optimize your workflow. Experience comfort, efficiency, and style with peripherals that complement your unique needs. Elevate your computing experience with the latest and most innovative peripheral equipment for both work and play.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Peripheral equipment"
                        },
                        new
                        {
                            Id = new Guid("042a0d33-d091-4a01-b63c-e676d879d4c8"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("78a7d439-5769-4a7d-8a14-d3f589e71b1f"),
                            Description = "Unleash your creativity with precision using our drawing tablets. Designed for digital artists and professionals, these tablets offer an immersive drawing experience with pressure-sensitive pens and responsive surfaces. Explore a range of sizes and features to suit your artistic needs, whether you're sketching, illustrating, or editing. Elevate your digital artistry with our advanced drawing tablets, combining technology and creativity seamlessly.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Drawing tablets"
                        },
                        new
                        {
                            Id = new Guid("7a28c90b-9a2e-4ab6-8255-7c7e6c653685"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("cdb59c3a-487c-42e5-bc0e-58ad5cfb93d3"),
                            Description = "Dive into a world of immersive gaming with the PlayStation console series. Whether you're a solo player or enjoy multiplayer experiences, PlayStation delivers cutting-edge technology, stunning graphics, and a vast library of games. From the latest releases to beloved classics, the PlayStation ecosystem offers entertainment for every gaming enthusiast. Elevate your gaming experience with the iconic PlayStation console, where innovation meets unparalleled gameplay.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "PlayStation"
                        },
                        new
                        {
                            Id = new Guid("17f2c0cc-38d3-452e-88ce-510090de2b92"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("cdb59c3a-487c-42e5-bc0e-58ad5cfb93d3"),
                            Description = "Unleash the power of gaming on the go with our cutting-edge gaming smartphones. Engineered for high-performance gaming experiences, these devices combine top-tier processors, advanced cooling systems, and immersive displays. Enjoy seamless gameplay, stunning graphics, and responsive controls as you dive into your favorite mobile games. Elevate your gaming journey with our gaming smartphones, where technology meets the thrill of unparalleled mobile gaming.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gaming smartphones"
                        },
                        new
                        {
                            Id = new Guid("dbbba1f1-e5fc-4f0e-bc4d-263d2cfe9290"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("cdb59c3a-487c-42e5-bc0e-58ad5cfb93d3"),
                            Description = "Enhance your mobile gaming experience with our gamepad for smartphones. Designed for comfort and precision, these controllers bring console-like gaming to your fingertips. With ergonomic designs and customizable buttons, our gamepads offer seamless control for a wide range of games. Elevate your mobile gaming adventures and enjoy immersive gameplay with the convenience of our responsive and versatile gamepads.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gamepad for smartphone"
                        },
                        new
                        {
                            Id = new Guid("29c45e6f-6a5e-4c46-a5ec-71a7c6ee81f8"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("cdb59c3a-487c-42e5-bc0e-58ad5cfb93d3"),
                            Description = "Dive into the world of immersive gaming with our high-performance gaming monitors. Engineered for speed and precision, these monitors boast high refresh rates, low input lag, and vibrant displays. Experience fluid graphics, sharp details, and responsive gameplay as you immerse yourself in your favorite titles. Whether you're a casual gamer or a competitive esports enthusiast, our gaming monitors redefine visual excellence for an unparalleled gaming experience.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gaming monitors"
                        },
                        new
                        {
                            Id = new Guid("17bbd60c-503a-46f4-9910-c44d2b7efba6"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("cdb59c3a-487c-42e5-bc0e-58ad5cfb93d3"),
                            Description = "Elevate your gaming setup with our premium game peripherals. From responsive keyboards and precision mice to immersive headsets and customizable controllers, our collection is designed to enhance every aspect of your gaming experience. Explore cutting-edge technology, ergonomic designs, and customizable features that cater to both casual and competitive gamers. Level up your gaming performance and immerse yourself in a world of unparalleled control and precision with our game peripherals.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Game peripherals"
                        },
                        new
                        {
                            Id = new Guid("8725ff1b-d64d-4f14-b0c1-663c16fdd554"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("cdb59c3a-487c-42e5-bc0e-58ad5cfb93d3"),
                            Description = "Upgrade and optimize your computing experience with our comprehensive range of computer parts. Explore powerful processors, high-capacity storage solutions, cutting-edge graphics cards, and fast memory options. Whether you're building a custom PC, enhancing gaming performance, or improving productivity, our selection of computer parts ensures top-tier quality, compatibility, and reliability for your computing needs.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Computer parts"
                        },
                        new
                        {
                            Id = new Guid("a41241d1-45ac-4715-8e92-9cbf9f9b3ef7"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("cdb59c3a-487c-42e5-bc0e-58ad5cfb93d3"),
                            Description = "Dive into an immersive gaming experience with our high-performance gaming monitors. Designed for speed and precision, these monitors deliver high refresh rates, low input lag, and vibrant displays. Enjoy fluid graphics, sharp details, and responsive gameplay as you plunge into your favorite titles. Whether you're a casual gamer or an esports enthusiast, our gaming monitors redefine visual excellence, offering an unparalleled and responsive gaming environment.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gaming monitors"
                        },
                        new
                        {
                            Id = new Guid("d0d7aa6e-bcb3-4c14-96f9-0a45e9149a67"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("cdb59c3a-487c-42e5-bc0e-58ad5cfb93d3"),
                            Description = "Unleash gaming excellence on the go with our cutting-edge gaming notebooks. Engineered for portable power, these laptops feature high-performance processors, powerful graphics cards, and high-refresh-rate displays. Immerse yourself in vivid graphics and responsive gameplay wherever you go. Whether you're a casual gamer or a competitive enthusiast, our gaming notebooks provide a perfect blend of performance, portability, and style for an exceptional gaming experience on the move.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gaming notebooks"
                        },
                        new
                        {
                            Id = new Guid("d1bba8aa-b0d4-42a7-b08f-71b5e7757cb3"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("cdb59c3a-487c-42e5-bc0e-58ad5cfb93d3"),
                            Description = "Dive into the gaming world with the Xbox console series. Designed for unparalleled entertainment, Xbox offers a vast library of games, stunning graphics, and immersive experiences. From the latest releases to classic favorites, the Xbox ecosystem caters to gamers of all tastes and preferences. Elevate your gaming journey with cutting-edge technology and a community that celebrates the love of gaming. Welcome to the next level of entertainment with Xbox.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Xbox"
                        },
                        new
                        {
                            Id = new Guid("7f9e65a1-6c4c-4dbb-a3d1-9e1c2b5b35b0"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("f6b3406c-6046-486f-8ba8-a896ac26fe90"),
                            Description = "Transform your kitchen into a culinary haven with our collection of great kitchen appliances. From high-performance blenders and versatile food processors to sleek coffee makers and efficient toasters, our appliances combine innovation and style. Experience the joy of cooking and entertaining with reliable, easy-to-use appliances that enhance your culinary skills. Elevate your kitchen experience with our range of appliances designed to make every meal a delight.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Great kitchen appliances"
                        },
                        new
                        {
                            Id = new Guid("e8a4d6b2-0b4f-4372-8292-665ae7d3f29e"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("f6b3406c-6046-486f-8ba8-a896ac26fe90"),
                            Description = "Elevate your dining experience with our exquisite collection of dishes. From elegant dinnerware sets to versatile serving plates, our dishes combine style and functionality. Explore a variety of designs, materials, and patterns to suit every occasion, from casual meals to formal gatherings. Create a visually appealing table setting with our high-quality dishes that add a touch of sophistication to your dining space.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dishes"
                        },
                        new
                        {
                            Id = new Guid("45c89a7f-fa4d-4c3d-9f21-827f11a9c834"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("f6b3406c-6046-486f-8ba8-a896ac26fe90"),
                            Description = "Optimize your food preparation process with our comprehensive collection of kitchen equipment. From high-performance blenders and food processors to reliable mixers and efficient chopping tools, our range is designed to enhance your culinary experience. Experience the joy of cooking with precision and ease using our innovative kitchen equipment. Elevate your culinary skills and create delicious meals with the right tools for every step of the preparation journey.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kitchen equipment for food preparation"
                        },
                        new
                        {
                            Id = new Guid("2b3fde56-118a-4f41-8a93-6fd157f2c4b5"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("f6b3406c-6046-486f-8ba8-a896ac26fe90"),
                            Description = "Upgrade your kitchen with our installed kitchen appliances, seamlessly blending form and function. From sleek built-in ovens and stylish cooktops to integrated refrigerators and advanced dishwashers, our collection combines modern design with cutting-edge technology. Experience the convenience of a well-equipped kitchen, where appliances are seamlessly integrated for a cohesive and efficient cooking space. Elevate your culinary environment with our range of installed kitchen appliances.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Installed kitchen appliances"
                        },
                        new
                        {
                            Id = new Guid("c09b1a8d-6922-47d2-8b9c-845c4a3cf79c"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("f6b3406c-6046-486f-8ba8-a896ac26fe90"),
                            Description = "Craft the perfect beverage with our premium drink preparation essentials. From state-of-the-art coffee makers and efficient tea infusers to innovative blenders for smoothies and cocktails, our collection ensures a delightful drink experience. Elevate your moments with precision and style, whether brewing your favorite coffee blend or concocting refreshing beverages. Embrace the art of drink preparation with our high-quality tools designed to enhance every sip.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Preparation of drink"
                        },
                        new
                        {
                            Id = new Guid("d0e3a99d-8d16-4a2a-81d6-5a9db9a40b28"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("9214f8c7-7c65-4c6d-852c-9f6f6c232a21"),
                            Description = "Transform your home into a haven of convenience and efficiency with our collection of great home appliances. From high-performance vacuum cleaners and energy-efficient washing machines to smart thermostats and innovative home security systems, our appliances enhance comfort and streamline daily tasks. Experience the latest in technology and design, ensuring that each appliance not only serves a purpose but also elevates your home living experience. Welcome to a smarter, more comfortable home with our range of great appliances.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Great appliances for the home"
                        },
                        new
                        {
                            Id = new Guid("a1f5c6b3-509d-43a8-8d38-745e20d8f48b"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("9214f8c7-7c65-4c6d-852c-9f6f6c232a21"),
                            Description = "Elevate your home living experience with our curated selection of small appliances. From compact coffee makers and versatile food processors to space-saving irons and efficient hand blenders, our collection combines functionality and style. Streamline daily tasks and add convenience to your routine with these thoughtfully designed appliances. Discover the perfect blend of performance and aesthetics, enhancing both the functionality and charm of your living space.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Small appliances for the home"
                        },
                        new
                        {
                            Id = new Guid("3c718a9b-8d43-4f45-8450-dce3627c3b04"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("9214f8c7-7c65-4c6d-852c-9f6f6c232a21"),
                            Description = "Create a comfortable and controlled environment with our advanced climate technology solutions. From smart thermostats and energy-efficient air purifiers to innovative heating and cooling systems, our collection is designed to enhance your indoor comfort. Experience the latest in climate control technology, optimizing energy efficiency and providing personalized settings for your home or office. Elevate your living and working spaces with our cutting-edge climate technology for a healthier, more comfortable environment.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Climate technology"
                        },
                        new
                        {
                            Id = new Guid("6e8a719f-1c35-49a3-9209-6a9f132d2f0f"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("9214f8c7-7c65-4c6d-852c-9f6f6c232a21"),
                            Description = "Enhance your control over the indoor environment with our range of climate accessories. From smart thermostats and air purifiers to efficient humidifiers and space heaters, our collection complements your climate control system. Create a personalized and comfortable atmosphere in every room with accessories designed for efficiency and convenience. Elevate your indoor experience with our climate accessories, ensuring a tailored and enjoyable environment throughout the seasons.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Climate accessories"
                        },
                        new
                        {
                            Id = new Guid("f2c4d60a-8e3a-4aa6-b8c6-754497a65a5b"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("9214f8c7-7c65-4c6d-852c-9f6f6c232a21"),
                            Description = "Discover a world of convenience and efficiency with our diverse range of household products. From cleaning essentials like vacuum cleaners and mops to organization solutions like storage containers and shelving units, our collection is designed to streamline your daily tasks. Experience the perfect blend of functionality and style as our household products enhance the comfort and aesthetics of your living space. Elevate your home living with our thoughtfully curated selection of essential household items.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Household products"
                        },
                        new
                        {
                            Id = new Guid("9d7f5e6a-20e3-4a57-b529-6d6f104e86c9"),
                            CreatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Current_Category_Id = new Guid("9214f8c7-7c65-4c6d-852c-9f6f6c232a21"),
                            Description = "Optimize the functionality and style of your home appliances with our range of accessories. From specialized attachments for kitchen appliances to add-ons for cleaning and maintenance tools, our collection is designed to enhance the performance and versatility of your household equipment. Explore thoughtful additions that cater to every need, ensuring a seamless and efficient experience with your appliances. Elevate the utility of your home appliances with our curated selection of accessories.",
                            LastUpdatedAt = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Accessories for home appliances"
                        });
                });

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Subcategory", b =>
                {
                    b.HasOne("Final_project_crud_endpoints.DataBase.Entities.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("Current_Category_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Final_project_crud_endpoints.DataBase.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
